CREATE PROCEDURE CREATE_SUBMISSION_TABLE @TABLE_NAME
AS
CREATE TABLE @TABLE_NAME(
	submission_id INTEGER NOT NULL,
	submit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY(submission_id)
);